version: 2.1
jobs:
  test:
    docker:
      - image: cimg/php:8.2
        environment:
          APP_ENV: testing
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_DATABASE: laravel_db
          DB_USERNAME: laravel_user
          DB_PASSWORD: laravel_pass

      - image: cimg/mysql:8.0
        command: mysqld --default-authentication-plugin=mysql_native_password
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: laravel_db
          MYSQL_USER: laravel_user
          MYSQL_PASSWORD: laravel_pass

    steps:
      - checkout
      - run:
          name: composer install
          working_directory: src
          command: composer install
      - run:
          name: run key generate
          working_directory: src
          command: php artisan key:generate
      - run:
          name: run migrate
          working_directory: src
          command: php artisan migrate --env=testing
      - run:
          name: run seed
          working_directory: src
          command: php artisan db:seed --env=testing
      - run:
          name: run test
          working_directory: src
          command: php artisan test --filter AdminTest

workflows:
  test_workflow:
    jobs:
      - test






